version: '3.2'

services: 
  python:
    image: tttest02/python:1.0
    build: ./python
    container_name: 'ex21_python'
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes: 
      - ../python:/tmp/work
    environment: 
      - DISPLAY=172.22.80.1:0.0